# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_public_v2_collaborationhub_projects_project_id_files_post_request import ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest

class TestApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest(unittest.TestCase):
    """ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest:
        """Test ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest`
        """
        model = ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest()
        if include_optional:
            return ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest(
                form_file = bytes(b'blah')
            )
        else:
            return ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest(
        )
        """

    def testApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest(self):
        """Test ApiPublicV2CollaborationhubProjectsProjectIdFilesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
