# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ibvcl_service_meta_entities_requests_public_v20_invite_subscription_user_request import IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest

class TestIBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest(unittest.TestCase):
    """IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest:
        """Test IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest`
        """
        model = IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest()
        if include_optional:
            return IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest(
                unique_device_id = '',
                invitation_accept_url = '',
                invitation_reject_url = '',
                message_theme = '',
                user = openapi_client.models.ibv/cl_service/meta_entities/requests/public/v2_0/invite_subscription_user_item.IBV.CLService.MetaEntities.Requests.Public.V2_0.InviteSubscriptionUserItem(
                    username = '', 
                    first_name = '', 
                    last_name = '', 
                    company_name = '', 
                    phone_number = '', 
                    language = '', )
            )
        else:
            return IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest(
        )
        """

    def testIBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest(self):
        """Test IBVCLServiceMetaEntitiesRequestsPublicV20InviteSubscriptionUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
