# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ibvcl_service_meta_entities_responses_public_common_get_subscription_users_item import IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem

class TestIBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem(unittest.TestCase):
    """IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem:
        """Test IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem`
        """
        model = IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem()
        if include_optional:
            return IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem(
                username = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 1,
                permission = 0
            )
        else:
            return IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem(
        )
        """

    def testIBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem(self):
        """Test IBVCLServiceMetaEntitiesResponsesPublicCommonGetSubscriptionUsersItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
