# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ibvcl_service_meta_entities_tile_pinned_state_enum import IBVCLServiceMetaEntitiesTilePinnedStateEnum

class TestIBVCLServiceMetaEntitiesTilePinnedStateEnum(unittest.TestCase):
    """IBVCLServiceMetaEntitiesTilePinnedStateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIBVCLServiceMetaEntitiesTilePinnedStateEnum(self):
        """Test IBVCLServiceMetaEntitiesTilePinnedStateEnum"""
        # inst = IBVCLServiceMetaEntitiesTilePinnedStateEnum()

if __name__ == '__main__':
    unittest.main()
