# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ibvcl_service_meta_entities_responses_public_common_subscription_user_status_enum import IBVCLServiceMetaEntitiesResponsesPublicCommonSubscriptionUserStatusEnum

class TestIBVCLServiceMetaEntitiesResponsesPublicCommonSubscriptionUserStatusEnum(unittest.TestCase):
    """IBVCLServiceMetaEntitiesResponsesPublicCommonSubscriptionUserStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIBVCLServiceMetaEntitiesResponsesPublicCommonSubscriptionUserStatusEnum(self):
        """Test IBVCLServiceMetaEntitiesResponsesPublicCommonSubscriptionUserStatusEnum"""
        # inst = IBVCLServiceMetaEntitiesResponsesPublicCommonSubscriptionUserStatusEnum()

if __name__ == '__main__':
    unittest.main()
