# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ibvcl_service_meta_entities_tile_blob_status import IBVCLServiceMetaEntitiesTileBlobStatus

class TestIBVCLServiceMetaEntitiesTileBlobStatus(unittest.TestCase):
    """IBVCLServiceMetaEntitiesTileBlobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIBVCLServiceMetaEntitiesTileBlobStatus(self):
        """Test IBVCLServiceMetaEntitiesTileBlobStatus"""
        # inst = IBVCLServiceMetaEntitiesTileBlobStatus()

if __name__ == '__main__':
    unittest.main()
