# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ibvcl_service_meta_entities_state_machine_status import IBVCLServiceMetaEntitiesStateMachineStatus

class TestIBVCLServiceMetaEntitiesStateMachineStatus(unittest.TestCase):
    """IBVCLServiceMetaEntitiesStateMachineStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIBVCLServiceMetaEntitiesStateMachineStatus(self):
        """Test IBVCLServiceMetaEntitiesStateMachineStatus"""
        # inst = IBVCLServiceMetaEntitiesStateMachineStatus()

if __name__ == '__main__':
    unittest.main()
