# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.public_api_api import PublicApiApi


class TestPublicApiApi(unittest.TestCase):
    """PublicApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicApiApi()

    def tearDown(self) -> None:
        pass

    def test_api_public_v2_collaborationhub_auth_token_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_auth_token_get

        Returns a user authorization token that can be used to make authenticated requests to the API.  This method uses the ApiKey provided in the Authorization header in the form Bearer {api-key}
        """
        pass

    def test_api_public_v2_collaborationhub_auth_userinfo_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_auth_userinfo_get

        Returns the current user details.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_owned_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_owned_get

        Returns a paged list of all projects owned by the calling user.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_participating_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_participating_get

        Returns a paged list of the project that the user participates in.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_post

        Creates a new project
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_copy_operation_id_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_copy_operation_id_get

        Returns the status of the project copy operation
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_copy_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_copy_post

        Copies the project with the given ID as a new project.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_delete(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_delete

        Deletes the project with the given ID.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_files_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_files_post

        Uploads a file on the server and creates the corresponding file tile.  This method will also trigger the image thumbnail generation, if applicable for the file type
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_get

        Returns a project
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_invitationlink_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_invitationlink_post

        Creates a link that can be used to invite a user to a project.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_patch(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_patch

        Updates the project with the given ID.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_tiles_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_tiles_get

        Returns a paged list of the tiles of the given project.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_tiles_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_tiles_post

        Creates a new tile.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_tiles_tile_id_delete(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_tiles_tile_id_delete

        Deletes a tile.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_users_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_users_get

        Returns a list of all users participating in the given project.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_users_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_users_post

        Adds a participant to a project.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_users_put(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_users_put

        Updates a project participant.
        """
        pass

    def test_api_public_v2_collaborationhub_projects_project_id_users_username_delete(self) -> None:
        """Test case for api_public_v2_collaborationhub_projects_project_id_users_username_delete

        Removes a participant from a project
        """
        pass

    def test_api_public_v2_collaborationhub_subscriptions_license_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_subscriptions_license_get

        Returns the current licensing information for the calling user.
        """
        pass

    def test_api_public_v2_collaborationhub_subscriptions_subscription_id_users_get(self) -> None:
        """Test case for api_public_v2_collaborationhub_subscriptions_subscription_id_users_get

        Removes a user from the given subscription.
        """
        pass

    def test_api_public_v2_collaborationhub_subscriptions_subscription_id_users_invite_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_subscriptions_subscription_id_users_invite_post

        Invites a user to the given subscription. This method will send an invitation email to the user, which the user can either accept or reject.
        """
        pass

    def test_api_public_v2_collaborationhub_subscriptions_subscription_id_users_post(self) -> None:
        """Test case for api_public_v2_collaborationhub_subscriptions_subscription_id_users_post

        Adds a user to the given subscription.
        """
        pass

    def test_api_public_v2_collaborationhub_subscriptions_subscription_id_users_username_delete(self) -> None:
        """Test case for api_public_v2_collaborationhub_subscriptions_subscription_id_users_username_delete

        Removes a user from the given subscription.
        """
        pass


if __name__ == '__main__':
    unittest.main()
