# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IBVCLServiceMetaEntitiesTileBlobStatus(int, Enum):
    """
    IBVCLServiceMetaEntitiesTileBlobStatus
    """

    """
    allowed enum values
    """
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_5 = 5
    NUMBER_6 = 6
    NUMBER_7 = 7
    NUMBER_10 = 10
    NUMBER_11 = 11

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IBVCLServiceMetaEntitiesTileBlobStatus from a JSON string"""
        return cls(json.loads(json_str))


