# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IBVCLServiceMetaEntitiesTileType(int, Enum):
    """
    IBVCLServiceMetaEntitiesTileType
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5
    NUMBER_6 = 6
    NUMBER_8 = 8
    NUMBER_9 = 9
    NUMBER_11 = 11
    NUMBER_12 = 12
    NUMBER_13 = 13
    NUMBER_16 = 16
    NUMBER_17 = 17
    NUMBER_18 = 18
    NUMBER_19 = 19
    NUMBER_20 = 20
    NUMBER_21 = 21
    NUMBER_22 = 22
    NUMBER_23 = 23
    NUMBER_24 = 24

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IBVCLServiceMetaEntitiesTileType from a JSON string"""
        return cls(json.loads(json_str))


