# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectRequest(BaseModel):
    """
    IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectRequest
    """ # noqa: E501
    unique_device_id: Optional[StrictStr] = Field(default=None, alias="uniqueDeviceId")
    description: Optional[StrictStr] = None
    background_color: Optional[StrictStr] = Field(default=None, alias="backgroundColor")
    is_activity_log_enabled: Optional[StrictBool] = Field(default=None, alias="isActivityLogEnabled")
    is_versioning_enabled: Optional[StrictBool] = Field(default=None, alias="isVersioningEnabled")
    __properties: ClassVar[List[str]] = ["uniqueDeviceId", "description", "backgroundColor", "isActivityLogEnabled", "isVersioningEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if background_color (nullable) is None
        # and model_fields_set contains the field
        if self.background_color is None and "background_color" in self.model_fields_set:
            _dict['backgroundColor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uniqueDeviceId": obj.get("uniqueDeviceId"),
            "description": obj.get("description"),
            "backgroundColor": obj.get("backgroundColor"),
            "isActivityLogEnabled": obj.get("isActivityLogEnabled"),
            "isVersioningEnabled": obj.get("isVersioningEnabled")
        })
        return _obj


