# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.ibvcl_service_meta_entities_project_participant_permission_enum import IBVCLServiceMetaEntitiesProjectParticipantPermissionEnum
from typing import Optional, Set
from typing_extensions import Self

class IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectInvitationRequest(BaseModel):
    """
    IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectInvitationRequest
    """ # noqa: E501
    unique_device_id: Optional[StrictStr] = Field(default=None, alias="uniqueDeviceId")
    email: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    member_permission: Optional[IBVCLServiceMetaEntitiesProjectParticipantPermissionEnum] = Field(default=None, alias="memberPermission")
    guest_permission: Optional[IBVCLServiceMetaEntitiesProjectParticipantPermissionEnum] = Field(default=None, alias="guestPermission")
    invitation_url: Optional[StrictStr] = Field(default=None, alias="invitationUrl")
    valid_for_minutes: Optional[StrictInt] = Field(default=None, alias="validForMinutes")
    password: Optional[StrictStr] = None
    guest_identification_required: Optional[StrictBool] = Field(default=None, alias="guestIdentificationRequired")
    message_theme: Optional[StrictStr] = Field(default=None, alias="messageTheme")
    __properties: ClassVar[List[str]] = ["uniqueDeviceId", "email", "notes", "memberPermission", "guestPermission", "invitationUrl", "validForMinutes", "password", "guestIdentificationRequired", "messageTheme"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectInvitationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if invitation_url (nullable) is None
        # and model_fields_set contains the field
        if self.invitation_url is None and "invitation_url" in self.model_fields_set:
            _dict['invitationUrl'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if message_theme (nullable) is None
        # and model_fields_set contains the field
        if self.message_theme is None and "message_theme" in self.model_fields_set:
            _dict['messageTheme'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IBVCLServiceMetaEntitiesRequestsPublicV20CreateProjectInvitationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uniqueDeviceId": obj.get("uniqueDeviceId"),
            "email": obj.get("email"),
            "notes": obj.get("notes"),
            "memberPermission": obj.get("memberPermission"),
            "guestPermission": obj.get("guestPermission"),
            "invitationUrl": obj.get("invitationUrl"),
            "validForMinutes": obj.get("validForMinutes"),
            "password": obj.get("password"),
            "guestIdentificationRequired": obj.get("guestIdentificationRequired"),
            "messageTheme": obj.get("messageTheme")
        })
        return _obj


