# coding: utf-8

"""
    Collaboard Public Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IBVCLServiceMetaEntitiesResponsesPublicCommonProject(BaseModel):
    """
    IBVCLServiceMetaEntitiesResponsesPublicCommonProject
    """ # noqa: E501
    project_id: Optional[StrictInt] = Field(default=None, alias="projectId")
    description: Optional[StrictStr] = None
    type: Optional[StrictInt] = None
    container_uri: Optional[StrictStr] = Field(default=None, alias="containerUri")
    background_color: Optional[StrictStr] = Field(default=None, alias="backgroundColor")
    created_by: Optional[StrictInt] = Field(default=None, alias="createdBy")
    created_by_user: Optional[StrictStr] = Field(default=None, alias="createdByUser")
    created_by_unique_machine_id: Optional[StrictStr] = Field(default=None, alias="createdByUniqueMachineId")
    creation_date: Optional[datetime] = Field(default=None, alias="creationDate")
    updated_by: Optional[StrictInt] = Field(default=None, alias="updatedBy")
    updated_by_user: Optional[StrictStr] = Field(default=None, alias="updatedByUser")
    last_update: Optional[datetime] = Field(default=None, alias="lastUpdate")
    zoom_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="zoomFactor")
    offset_x: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="offsetX")
    offset_y: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="offsetY")
    presenter: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["projectId", "description", "type", "containerUri", "backgroundColor", "createdBy", "createdByUser", "createdByUniqueMachineId", "creationDate", "updatedBy", "updatedByUser", "lastUpdate", "zoomFactor", "offsetX", "offsetY", "presenter"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IBVCLServiceMetaEntitiesResponsesPublicCommonProject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if container_uri (nullable) is None
        # and model_fields_set contains the field
        if self.container_uri is None and "container_uri" in self.model_fields_set:
            _dict['containerUri'] = None

        # set to None if background_color (nullable) is None
        # and model_fields_set contains the field
        if self.background_color is None and "background_color" in self.model_fields_set:
            _dict['backgroundColor'] = None

        # set to None if created_by_user (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_user is None and "created_by_user" in self.model_fields_set:
            _dict['createdByUser'] = None

        # set to None if updated_by_user (nullable) is None
        # and model_fields_set contains the field
        if self.updated_by_user is None and "updated_by_user" in self.model_fields_set:
            _dict['updatedByUser'] = None

        # set to None if presenter (nullable) is None
        # and model_fields_set contains the field
        if self.presenter is None and "presenter" in self.model_fields_set:
            _dict['presenter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IBVCLServiceMetaEntitiesResponsesPublicCommonProject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "projectId": obj.get("projectId"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "containerUri": obj.get("containerUri"),
            "backgroundColor": obj.get("backgroundColor"),
            "createdBy": obj.get("createdBy"),
            "createdByUser": obj.get("createdByUser"),
            "createdByUniqueMachineId": obj.get("createdByUniqueMachineId"),
            "creationDate": obj.get("creationDate"),
            "updatedBy": obj.get("updatedBy"),
            "updatedByUser": obj.get("updatedByUser"),
            "lastUpdate": obj.get("lastUpdate"),
            "zoomFactor": obj.get("zoomFactor"),
            "offsetX": obj.get("offsetX"),
            "offsetY": obj.get("offsetY"),
            "presenter": obj.get("presenter")
        })
        return _obj


